### ISSUE TITLE
Allow change playbackrate

### ISSUE THREAD

**Issue by ghost** [tong/atom-videoplayer#10]
Thanks @tong for the great work you have done, I love your atom package because it allows me to be more productive while taking notes on the videos. Would it be possible to add the option to speed up the video?

**Comment by tong** [comment]
Yes, i think i can do that coming days.

**Comment by tong** [comment]
I've just published v1.7.0.
You can increase/decrease playbackrate with `u/i` and reset to default rate by right-click → `Reset playbackrate`

**Comment by ghost** [comment]
Fantastic! it works very well.
thank you very much
